M48
; DRILL file KiCad 10.0.5 date 2026-08-18T14:00:32
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-18T14:00:32-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X131.69Y-118.85
X131.69Y-121.85
T2
X132.5Y-113.0
X132.5Y-137.0
X164.0Y-113.0
X164.0Y-137.0
M30
